version: "3.9"
services:
  folder-profiller:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GOOS: ${GOOS}
      GOARCH: ${GOARCH}
      BIN_FILE_NAME: ${BIN_FILE_NAME}
    volumes:
      - .:/app